name : Platform land
brand : Platform land
description : A project to explore how digital platforms will change government and society
keyword : 
url : https://platformland.github.io
email : richard@richardpope.org
twitter : 
github : platformland
author : Richard Pope
year : 2018
markdown : kramdown
destination : docs
exclude :
  - node_modules
scholar:
  bibliography_template: bibliography
  source: bibliography
  style: chicago-annotated-bibliography
  sort_by: title
plugins: ['jekyll/scholar']
