name : Platform Land
brand : Platform Land
description : A project to explore how digital platforms will change government and society
keyword : 
url : https://platformland.github.io
email : richard_pope@hks.harvard.edu
twitter : 
github : platformland
author : Richard Pope
year : 2018
markdown : kramdown
exclude :
  - node_modules

plugins :
  - jekyll-scholar
